#pragma config(Sensor, port9,  lightSensor,    sensorVexIQ_ColorGrayscale)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int calcThresh(tSensors sensor)
{
	int black = 1000;
	int white = -666;

	int startTime = nPgmTime;
	while(nPgmTime-startTime < 5000)
	{

		//put code here
		if(getColorGrayscale(lightSensor) > white)
		{
			white = getColorGrayscale(lightSensor);
		}

		if(getColorGrayscale(lightSensor) < black)
		{
			black = getColorGrayscale(lightSensor);
		}
	}
	int Threshold = (white + black) /2;

	displayVariableValues(line3,Threshold);
	displayVariableValues(line4,white);
	displayVariableValues(line5,black);
	sleep(3000);

	return Threshold;
}



//1. get the lightsensor value
//2. check if that is whiter then our whitest white
//3. check if that is blacker than our blackest black
//Calcuate threshhold
task main()
{
	int lsThresh = calcThresh(lightSensor);
}
