#pragma config(Motor,  motor1,          LMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          RMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorBrakeMode(LMotor, motorCoast);
	repeat(forever)
	{
		setMotorSpeed( LMotor, 0);

	}



}
