#pragma config(Motor,  motor7,          LHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          Strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor9,          Arm,           tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,         RHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         RMotor,        tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//CHA Vertical Travel
	//CHB Yaw
	//CHC Horizontal Travel

	int Lherding1, Lherding2, Rherding1, Rherding2, ReadyGrab, Grab;
	//CHD Arm
	unsigned long LHerderTime, RHerderTime;

	bool ROverride, LOverride;

	while(true){
		//Grab the joystick values and save them into variables
		//The float type means floating point or decimal
		float speedInput = getJoystickValue(ChA);
		float turnInput = getJoystickValue(ChB);
		float strafeInput = getJoystickValue(ChC);
		float armInput = getJoystickValue(ChD);


		if(Lherding1 == false && getJoystickValue(BtnEUp) == true) {setMotorTarget(LHerder, 75, 25); LOverride = true;}
		if(Lherding2 == false && getJoystickValue(BtnEDown) == true) {LHerderTime = nPgmTime+500; LOverride = false;}




		if(LHerderTime > nPgmTime && !LOverride) setMotor(LHerder, -25);
		else if(!LOverride) setMotor(LHerder, 0);

		if(Rherding1 == false && getJoystickValue(BtnFUp) == true) {setMotorTarget(RHerder, 75, 25); ROverride = true;}
		if(Rherding2 == false && getJoystickValue(BtnFDown) == true) {RHerderTime = nPgmTime+500; ROverride = false;}

		if(RHerderTime > nPgmTime && !ROverride) setMotor(RHerder, -25);
		else if(!ROverride) setMotor(RHerder, 0);

		if(ReadyGrab == false && getJoystickValue(BtnLUp) == true) {setMotorTarget(Arm, 325, 100); sleep(750);}
		if(Grab == false && getJoystickValue(BtnRUp) == true){
			setMotorTarget(Arm, 300, 100);
			setMotor(LMotor, 50);
			setMotor(RMotor, 50);
			sleep(750);
		}

		Lherding1 = getJoystickValue(BtnEUp);
		Lherding2 = getJoystickValue(BtnEDown);
		Rherding1 = getJoystickValue(BtnFUp);
		Rherding2 = getJoystickValue(BtnFDown);

		ReadyGrab = getJoystickValue(BtnLUp);
		Grab = getJoystickValue(BtnRUp);

		//check if controller value is small enough
		//if it is make it zero
		//this accounts for the poor build of certain controllers minimizing drift
		//abs will remove the negative sign from a number
		if(abs(speedInput) < 0.2) speedInput = 0;
		if(abs(turnInput) < 0.2) turnInput = 0;
		if(abs(strafeInput) < 0.4) strafeInput = 0;
		if(abs(armInput) < 0.4) armInput = 0;

		//Set the drive motors
		//this is an arcade format
		setMotor(LMotor, speedInput-turnInput);
		setMotor(RMotor, speedInput+turnInput);

		//Set the arm and strafe motors



		//TODO: add safety

		if(getMotorEncoder(Arm) <= 0 && armInput < 0){
			setMotor(Arm,0);
		}
		if(getMotorEncoder(Arm) >= 500 && armInput > 0){
			setMotor(Arm,0);
		}
		else{
			setMotor(Arm, armInput);
			setMotor(Strafe, strafeInput);





		}
	}


}
