#pragma config(Motor,  motor1,          LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          Strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          RHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          LHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          Arm,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          RMotor,           tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//CHA Vertical Travel
	//CHB Yaw
	//CHC Horizontal Travel
	//CHD Arm

	while(true){
		//Grab the joystick values and save them into variables
		//The float type means floating point or decimal
		float moving = getJoystickValue(ChA);
		float turning = getJoystickValue(ChB);
		float strafing = getJoystickValue(ChC);
		float arming = getJoystickValue(ChD);
		bool Lherding1 = getJoystickValue(BtnEUp);
		bool Lherding2 = getJoystickValue(BtnEDown);
		bool Rherding1 = getJoystickValue(BtnFUp);
		bool Rherding2 = getJoystickValue(BtnFDown);
		if(Lherding1 == false && Lherding2 == true) setMotortarget(LHerder, 45, 50);
		if(Lherding1 == true && Lherding2 == false) setMotorTarget(LHerder, 0,50);


		if(Rherding1 == false && Rherding2 == true) setmotortarget(RHerder, 45, 50);
		if(Rherding1 == true && Rherding2 == false) setMotorTarget(RHerder, 0,50);


		//check if controller value is small enough
		//if it is make it zero
		//this accounts for the poor build of certain controllers minimizing drift
		//abs will remove the negative sign from a number
		if(abs(moving) < 0.1) moving = 0;
		if(abs(turning) < 0.1) turning = 0;
		if(abs(strafing) < 0.1) strafing = 0;
		if(abs(arming) < 0.1) arming = 0;

		//Set the drive motors
		//this is an arcade format
		setMotor(LMotor, moving-turning);
		setMotor(RMotor, moving+turning);

		//Set the arm and strafe motors
		setMotor(Arm, arming);
		setMotor(Strafe, strafing);

		//TODO: add the herders
		//TODO: add safety
	}


}
