#pragma config(Sensor, port7,  LightSensorLeft, sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port8,  LightSensorRight, sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  LightSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          RightDrive,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          RHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          StrafeDrive,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          ArmMotor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          LHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          LeftDrive,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//CHA Vertical Travel
//CHB Yaw
//CHC Horizontal Travel
//CHD Arm

	while(true){
		//Grab the joystick values and save them into variables
		//The float type means floating point or decimal
		float VMoving = getJoystickValue(ChA);
		float Turning = getJoystickValue(ChB);
		float HMoving = getJoystickValue(ChC);
		float armMoving = getJoystickValue(ChD);
		bool Lherding1 = getJoystickValue (BtnEUp);
		bool Lherding2 = getJoystickValue (BtnEDown);
		bool Rherding1 = getJoystickValue (BtnFUp);
		bool Rherding2 = getJoystickValue (BtnFDown);


		if(Lherding1 == false && getJoystickValue(BtnEUp) == true )setMotorTarget (LHerder, 45, 50);
		if(Lherding2 == false && getJoystickValue(BtnEDown) == true )setMotorTarget (LHerder,-45, 50);
		if(Rherding1 == false && getJoystickValue(BtnFUp) == true)setMotorTarget (RHerder, 45, 50);
		if(Rherding2 == false && getJoystickValue(BtnFUp) == true)setMotorTarget (RHerder, -45, 50);




		//check if controller value is small enough
		//if it is make it zero
		//this accounts for the poor build of certain controllers minimizing drift
		//abs will remove the negative sign from a number
		if(abs(VMoving) < 0.1) VMoving = 0;
		if(abs(Turning) < 0.1) Turning = 0;
		if(abs(HMoving) < 0.1) HMoving = 0;
		if(abs(armMoving) < 0.1) armMoving = 0;


		//yaa

		//Set the drive motors
		//this is an arcade format
		setMotor(LeftDrive, VMoving-Turning);
		setMotor(RightDrive, VMoving+Turning);

		//Set the arm and strafe motors
		setMotor(ArmMotor, HMoving);
		setMotor(StrafeDrive, armMoving);

		//TODO: add the herders
		//TODO: add safety

		//Set the herders
		setMotor(LHerder, Lherding1);
	}
}
