#pragma config(Motor,  motor1,          LMotor,        tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RMotor,        tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void waitForMotor(tMotor nMotorIndex) {

	while(getMotorZeroVelocity(nMotorIndex)){sleep(10);}

	while(!getMotorZeroVelocity(nMotorIndex)){sleep(10);}
}


task main()
{
setMotorTarget(LMotor,360,50);
setMotorTarget(RMotor,360,50);
waitForMotor(LMotor);
stopAllMotors();
}
