#pragma config(Sensor, port7,  TouchSensor,    sensorVexIQ_LED)
#pragma config(Sensor, port8,  RBLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, MLs,            sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, RFLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          LArm,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          RArm,          tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          RHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{

int MLsThresh, RFLsThresh;

MLsThresh = 90;
RFLsThresh = 90;

int calcThresh(tSensors sensor)

void lineFollow(tSensors sensor, int LSpeed, int RSpeed, int Thresh){
	if(getColorGrayscale(sensor) > Thresh){
		setMotor(LMotor, LSpeed);
		setMotor(RMotor, RSpeed);
		}else{
		setMotor(LMotor, RSpeed);
		setMotor(RMotor, LSpeed);
	}
}
while(getColorGrayscale(MLs) < MLsThresh){
		lineFollow(RFLs, -50, -20, RFLsThresh);
	}
	sleep(500);
	while(getColorGrayscale(MLs) > MLsThresh){
		lineFollow(RFLs, -50, -20, RFLsThresh);
	}
	sleep(500);
	while(getColorGrayscale(MLs) < MLsThresh){
		lineFollow(RFLs, -50, -30, RFLsThresh);
	}
	sleep(500);
	while(getColorGrayscale(MLs) > MLsThresh){
		lineFollow(RFLs, -50, -32, RFLsThresh);
	}

}
