#pragma config(Sensor, port7,  TouchSensor,    sensorVexIQ_LED)
#pragma config(Sensor, port8,  LFLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, MLs,            sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, RFLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          LArm,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          RArm,          tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          RHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




task main()
{

repeat(forever){displayTextLine(line1, "%d", getColorGrayscale(LFLs));}

}
