#pragma config(Motor,  motor7,          RightDrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor8,          RHerder,       tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor9,          ArmMotor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         StrafeDrive,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         LHerder,       tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor12,         LeftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//CHA Vertical Travel
//CHB Yaw
//CHC Horizontal Travel
//CHD Arm

	while(true){
		//Grab the joystick values and save them into variables
		//The float type means floating point or decimal
		float VMoving = getJoystickValue(ChB);
		float Turning = getJoystickValue(ChA);
		float HMoving = getJoystickValue(ChD);
		float armMoving = getJoystickValue(ChC);
		int Lherding1 = getJoystickValue (BtnEUp);
		int Lherding2 = getJoystickValue (BtnEDown);
		int Rherding1 = getJoystickValue (BtnFUp);
		int Rherding2 = getJoystickValue (BtnFDown);


		if(Lherding1 == false && getJoystickValue(BtnEUp) == true )setMotorTarget (LHerder, 45, 50);
		if(Lherding2 == false && getJoystickValue(BtnEDown) == true )setMotorTarget (LHerder,-45, 50);
		if(Rherding1 == false && getJoystickValue(BtnFUp) == true)setMotorTarget (RHerder, 45, 50);
		if(Rherding2 == false && getJoystickValue(BtnFUp) == true)setMotorTarget (RHerder, -45, 50);




		//check if controller value is small enough
		//if it is make it zero
		//this accounts for the poor build of certain controllers minimizing drift
		//abs will remove the negative sign from a number
		if(abs(VMoving) < 0.1) VMoving = 0;
		if(abs(Turning) < 0.1) Turning = 0;
		if(abs(HMoving) < 0.1) HMoving = 0;
		if(abs(armMoving) < 0.1) armMoving = 0;


		//yaa

		//Set the drive motors
		//this is an arcade format
		setMotor(LeftDrive, VMoving+Turning);
		setMotor(RightDrive, VMoving-Turning);

		//Set the arm and strafe motors
		setMotor(ArmMotor, HMoving);
		setMotor(StrafeDrive, armMoving);

		//TODO: add the herders
		//TODO: add safety

		//Set the herders
		setMotor(LHerder, Lherding1);
	}
}
