#pragma config(Sensor, port7,  TouchSensor,    sensorVexIQ_LED)
#pragma config(Sensor, port8,  RBLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, MLs,            sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, RFLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          LArm,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          RArm,          tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          RHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
//CHA Vertical Travel
//CHB Yaw
//CHC Horizontal Travel
//CHD Arm

	while(true){
		//Grab the joystick values and save them into variables
		//The float type means floating point or decimal
		float VMoving = getJoystickValue(ChB);
		float Turning = getJoystickValue(ChA);
		float HMoving = getJoystickValue(ChD);
		float armMoving = getJoystickValue(ChC);
		int Lherding1 = getJoystickValue (BtnEUp);
		int Lherding2 = getJoystickValue (BtnEDown);
		int Rherding1 = getJoystickValue (BtnFUp);
		int Rherding2 = getJoystickValue (BtnFDown);


		if(Lherding1 == false && getJoystickValue(BtnEUp) == true )setMotorTarget (LHerder, 45, 50);
		if(Lherding2 == false && getJoystickValue(BtnEDown) == true )setMotorTarget (LHerder,-45, 50);
		if(Rherding1 == false && getJoystickValue(BtnFUp) == true)setMotorTarget (RHerder, 45, 50);
		if(Rherding2 == false && getJoystickValue(BtnFUp) == true)setMotorTarget (RHerder, -45, 50);




		//check if controller value is small enough
		//if it is make it zero
		//this accounts for the poor build of certain controllers minimizing drift
		//abs will remove the negative sign from a number
		if(abs(VMoving) < 0.1) VMoving = 0;
		if(abs(Turning) < 0.1) Turning = 0;
		if(abs(HMoving) < 0.1) HMoving = 0;
		if(abs(armMoving) < 0.1) armMoving = 0;


		//yaa

		//Set the drive motors
		//this is an arcade format
		setMotor(LMotor, VMoving+Turning);
		setMotor(RMotor, VMoving-Turning);

		//Set the arm and strafe motors
		setMotor(RArm, HMoving);
		setMotor(LArm, HMoving);

		//TODO: add the herders
		//TODO: add safety

		//Set the herders
		setMotor(LHerder, Lherding1);
	}
}
