#pragma config(Sensor, port7,  TouchSensor,    sensorVexIQ_LED)
#pragma config(Sensor, port8,  RBLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, MLs,            sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, RFLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          LArm,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          RArm,          tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          RHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//variable

int calcThresh(tSensors sensor)
{
	int black = 1000;
	int white = -666;

	//StartTime is equal to nPGMtime
	//nPGMtime is now 2001
	//nPgmTime subtracted by startTime is 1 which is less than 5000
	//This while loop runs for 5 secs

	int startTime = nPgmTime;
	while(nPgmTime-startTime < 5000)
	{
		sleep(50);
		//Detects the brightes white
		if(getColorGrayscale(sensor) > white)
		{
			white = getColorGrayscale(sensor);
		}
		//Detects the darkest black
		if(getColorGrayscale(sensor) < black)
		{
			black = getColorGrayscale(sensor);

		}
	}
	//Calculates Threshold
	int Threshold = (white + black) /2;
	//Displays the treshold, white, and black
	displayVariableValues(line3,Threshold);
	displayVariableValues(line4,white);
	displayVariableValues(line5,black);
	//Wait 3 secs
	sleep(3000);
	//returns threshold
	return Threshold;
}
//function to stop at black line
void waitForBlack(tSensors sensor,int threshold)
{
	repeatUntil(getColorGrayscale(sensor) <=  threshold)
	{
		sleep(10);
	}
}
///function to stop at white line
void waitForWhite(tSensors sensor,int threshold)
{
	repeatUntil(getColorGrayscale(sensor) >=  threshold)
	{
		sleep(10);
	}
}
//function to stop after a few lines
void wait4lines(tSensors sens,int threshold ,int numLines)
{
	repeat(numLines)
	{
		waitForBlack(sens,threshold);
		waitForWhite(sens,threshold);
	}
}

void lineFollow(tSensors sensor, int LSpeed, int RSpeed, int Thresh){
	if(getColorGrayscale(sensor) > Thresh){
		setMotor(LMotor, LSpeed);
		setMotor(RMotor, RSpeed);
		}else{
		setMotor(LMotor, RSpeed);
		setMotor(RMotor, LSpeed);
	}
}
//1. get the lightsensor value
//2. check if that is whiter then our whitest white
//3. check if that is blacker than our blackest black
//Calcuate threshhold

//main task
task main()
{

	int RFLsThresh, MLsThresh, RBLsThresh;

	//INIT
	//Wait for sensors to start up
	writeDebugStreamLine("%d", getColorGrayscale(RFLs));
	writeDebugStreamLine("%d", getColorGrayscale(MLs));
	sleep(1000);

	setTouchLEDColor(TouchSensor, colorBlue);
	waitUntil(getTouchLEDValue(TouchSensor));
	setTouchLEDColor(TouchSensor,colorYellow);

	//MLsThresh = calcThresh(MLs);
	//RFLsThresh = calcThresh(RFLs);

	MLsThresh = 90;
	RFLsThresh = 90;


	displayTextLine(line1, "RFLs = %d", RFLsThresh);
	displayTextLine(line1, "MLs = %d", MLsThresh);

	setTouchLEDColor(TouchSensor, colorRed);

	waitUntil(getTouchLEDValue(TouchSensor));

	/**/


	//Start Main Program
	resetGyro(Gyro);
	resetMotorEncoder(LMotor);
	resetMotorEncoder(RMotor);
	resetMotorEncoder(LArm);
	resetMotorEncoder(RArm);
	resetMotorEncoder(LHerder);
	resetMotorEncoder(RHerder);


	//Herders up
	setMotorTarget(LHerder, 57, 20);
	setMotorTarget(RHerder, 57, 20);

	//Turn 45 degrees
	setMotor(LMotor, 60);
	setMotor(RMotor, -20);
	waitUntil(getGyroDegrees(Gyro) < -60);

	setMotor(LMotor, 45);
	setMotor(RMotor, 15);

	waitForBlack(RFLs, RFLsThresh);
	setMotor(LMotor, 30);
	setMotor(RMotor, 20);
	sleep(1000);


	while(getColorGrayscale(MLs) < MLsThresh){
		lineFollow(RFLs, 50, 20, RFLsThresh);
	}
	sleep(500);
	while(getColorGrayscale(MLs) > MLsThresh){
		lineFollow(RFLs, 50, 20, RFLsThresh);
	}
	sleep(500);
	while(getColorGrayscale(MLs) < MLsThresh){
		lineFollow(RFLs, 50, 30, RFLsThresh);
	}
	sleep(500);
	while(getColorGrayscale(MLs) > MLsThresh){
		lineFollow(RFLs, 50, 32, RFLsThresh);
	}

	resetGyro(Gyro);
	resetMotorEncoder(RHerder);
	resetMotorEncoder(LHerder);

	setMotor(LMotor, -35);
	setMotor(RMotor, 35);
	waitUntil(getGyroDegrees(Gyro) > 10);

	setMotor(RHerder, -50);
	sleep(750);
	setMotor(RHerder, 0);

	resetGyro(Gyro);

	setMotor(LMotor, 35);
	setMotor(RMotor, -35);
	waitUntil(getGyroDegrees(Gyro) < -10);

	repeat(forever){

	if(getColorValue(RFLs) < 90 && getColorValue(RBLs) < 90){
		setMotor(LMotor, 50);
		setMotor(RMotor, 60);
	}

	if(getColorValue(RFLs) > 90 && getColorValue(RBLs) < 90){
		setMotor(LMotor, 60);
		setMotor(RMotor, 50);

	}
	if(getColorValue(RFLs) < 90 && getColorValue(RBLs) > 90){
		setMotor(LMotor, 50);
		setMotor(RMotor, 50);
	}
	if(getColorValue(RFLs) > 90 && getColorValue(RBLs) > 90){
		setMotor(LMotor, 50);
		setMotor(RMotor, 50);
	}
}

	/*

		while(getColorGrayscale(MLs) < MLsThresh){
		lineFollow(RBLs, -50, -20,RBLsThresh );
	}
	sleep(500);
	while(getColorGrayscale(MLs) > MLsThresh){
		lineFollow(RBLs, -50, -20,RBLsThresh );
	}
	sleep(500);
	while(getColorGrayscale(MLs) < MLsThresh){
		lineFollow(RBLs, -50, -30,RBLsThresh );
	}
	sleep(500);
	while(getColorGrayscale(MLs) > MLsThresh){
		lineFollow(RBLs, - 50, -32,RBLsThresh );
}

	resetGyro(Gyro);

	setMotor(LMotor, -35);
	setMotor(RMotor, 35);
	waitUntil(getGyroDegrees(Gyro) > 7);



	//Turn 45 degrees then start waiting on the lint Sensor
	//Agressive line follow

	/**/



	//Tap touch sensor to start threshold calculation
	//run threshold calculation
	//print thresholds on the screen

	//Wait for tap sensor
	//Start main program
	//variable

}
