#pragma config(Sensor, port2,  lightSensorLeft, sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port3,  lightSensorRight, sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  lightSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          LMotor,        tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RMotor,        tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//variable
int calcThresh(tSensors sensor)
{
	int black = 1000;
	int white = -666;

//StartTime is equal to nPGMtime
//nPGMtime is now 2001
//nPgmTime subtracted by startTime is 1 which is less than 5000
//This while loop runs for 5 secs

	int startTime = nPgmTime;
	while(nPgmTime-startTime < 5000)
	{
        sleep(50);
        //Detects the brightes white
		if(getColorGrayscale(sensor) > white)
		{
			white = getColorGrayscale(sensor);
		}
        //Detects the darkest black
		if(getColorGrayscale(sensor) < black)
		{
			black = getColorGrayscale(sensor);
		}
	}
    //Calculates Threshold
	int Threshold = (white + black) /2;
    //Displays the treshold, white, and black
	displayVariableValues(line3,Threshold);
	displayVariableValues(line4,white);
	displayVariableValues(line5,black);
    //Wait 3 secs
	sleep(3000);
    //returns threshold
	return Threshold;
}

//function to stop at black line
void waitForBlack(tSensors sensor,int threshold)
{
	repeatUntil(getColorGrayscale(sensor) <=  threshold)
	{
		sleep(10);
	}
}

//function to stop at white line
void waitForWhite(tSensors sensor,int threshold)
{
	repeatUntil(getColorGrayscale(sensor) >=  threshold)
	{
		sleep(10);
	}
}

//function to stop after a few lines
void wait4lines(tSensors sens,int threshold ,int numLines)
{
  repeat(numLines)
  {
	  waitForBlack(sens,threshold);
	  waitForWhite(sens,threshold);
  }
}

//1. get the lightsensor value
//2. check if that is whiter then our whitest white
//3. check if that is blacker than our blackest black
//Calcuate threshhold

//main task
task main()
{
    //variable
	int lsThresh = calcThresh(lightSensor);
    //forward
	setMotorSpeed(LMotor,50);
	setMotorSpeed(RMotor,50);
    //detects when to stop
	waitForBlack(lightSensor,lsThresh);
	waitForWhite(lightSensor,lsThresh);
	waitForBlack(lightSensor,lsThresh);
    //Stop motors
	stopAllMotors();
}\
