#pragma config(Motor,  motor1,          LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          Strafe,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          RHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          LHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          Arm,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          RMotor,           tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//CHA Vertical Travel
	//CHB Yaw
	//CHC Horizontal Travel
	//CHD Arm

	while(true){
		//Grab the joystick values and save them into variables
		//The float type means floating point or decimal
		float moving = getJoystickValue(ChA);
		float turning = getJoystickValue(ChB);
		float strafing = getJoystickValue(ChC);
		float arming = getJoystickValue(ChD);

		if(Lherding1 == false && Lherding2 = true) setmotortarget(LHerder, 45, 50);
		if(Lherding1 == true && Lherding2 = false) setMotorTarget(LHerder, 0,50);


		if(Rherding1 = false && Rherding2 = true) setmotortarget(RHerder, 45, 50);
		if(Rherding1 == true && Rherding2 = false) setMotorTarget(RHerder, 0,50);

		float Lherding1 == getJoystickValue(BtnEUp);
		float Lherding2 == getJoystickValue(BtnEDown);

		float Rherding1 == getJoystickValue(BtnFUp);
		float Rherding2 == getJoystickValue(BtnFDown);


		//check if controller value is small enough
		//if it is make it zero
		//this accounts for the poor build of certain controllers minimizing drift
		//abs will remove the negative sign from a number
		if(abs(moving) < 0.1) moving = 0;
		if(abs(turning) < 0.1) turn = 0;
		if(abs(strafing) < 0.1) strafing = 0;
		if(abs(arming) < 0.1) arming = 0;
		if(abs(Lherding1) < 0.1) Lherding1 = 0;
		if(abs(Lherding2) < 0.1) Lherding2 = 0;
		if(abs(Rherding1) < 0.1) Rherding1 = 0;
		if(abs(Rherding2) < 0.1) Rherding2 = 0;

		//Set the drive motors
		//this is an arcade format
		setMotor(LMotor, moving-turning);
		setMotor(RMotor, moving+turning);

		//Set the arm and strafe motors
		setMotor(Arm, arming);
		setMotor(Strafe, strafing);

		//TODO: add the herders
		//TODO: add safety
	}


}
