#pragma config(Sensor, port2,  LFLs,          sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port3,  TouchSensor,    sensorVexIQ_LED)
#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port5,  RFLs,           sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port6,  MLs,            sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor7,          RHerder,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          RMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor9,          LHerder,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         LArm,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         RArm,          tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         LMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
	displayTextLine(line1, "RFLs = %d", getColorGrayscale(RFLs));
	displayTextLine(line2, "MLs = %d", getColorGrayscale(MLs));
}


}
